# Generated by Django 2.2.4 on 2019-08-02 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='messageMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30, verbose_name='邮箱号码')),
                ('message', models.CharField(max_length=1024, verbose_name='邮件内容')),
                ('done', models.BooleanField(verbose_name='是否被处理')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='处理时间')),
            ],
        ),
    ]
