# Generated by Django 2.2.4 on 2019-08-04 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemail',
            name='done',
        ),
        migrations.RemoveField(
            model_name='messagemail',
            name='userName',
        ),
        migrations.AddField(
            model_name='messagemail',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='联系邮箱'),
        ),
        migrations.AddField(
            model_name='messagemail',
            name='isOpen',
            field=models.BooleanField(default=False, verbose_name='是否公开'),
        ),
        migrations.AddField(
            model_name='messagemail',
            name='name',
            field=models.CharField(default='没留名的小坏蛋', max_length=30, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='messagemail',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='留言时间'),
        ),
        migrations.AlterField(
            model_name='messagemail',
            name='message',
            field=models.CharField(default='刘明', max_length=1024, verbose_name='留言内容'),
        ),
    ]
